apiVersion: apps/v1
kind: Deployment
metadata:
  name: pstore-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pstore-app
  template:
    metadata:
      labels:
        app: pstore-app
    spec:
      containers:
      - name: pstore-app
        image: wilconsadocker/pizzastore:@@VERSION@@
        ports:
        - containerPort: 8080
#      nodeName: wnode2
---
apiVersion: v1
kind: Service
metadata:
  name: my-pstore-lb
spec:
  type: LoadBalancer
  selector:
    app: pstore-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 32150
# externalTrafficPolicy: Local
